// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

import (
	"time"
)

// サンプル作成の入力
type CreateSampleXInput struct {
	// 文字列値
	StringVal string `json:"stringVal"`
	// 整数値
	IntVal int `json:"intVal"`
	// 文字列配列
	ArrayVal []string `json:"arrayVal"`
	// メールアドレス
	Email string `json:"email"`
}

// サンプル作成のレスポンス
type CreateSampleXPayload struct {
	// 作成されたサンプル
	Sample *SampleX `json:"sample"`
}

type Mutation struct {
}

type Query struct {
}

type SampleX struct {
	// サンプルの一意識別子
	ID string `json:"id"`
	// 文字列値
	StringVal string `json:"stringVal"`
	// 整数値
	IntVal int `json:"intVal"`
	// 文字列配列
	ArrayVal []string `json:"arrayVal"`
	// メールアドレス
	Email string `json:"email"`
	// 作成日時
	CreatedAt time.Time `json:"createdAt"`
	// 更新日時
	UpdatedAt time.Time `json:"updatedAt"`
}
