// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/NishimuraTakuya-nt/go-graphql/internal/adapters/primary/graphql/resolvers"
	"github.com/NishimuraTakuya-nt/go-graphql/internal/core/usecases"
)

// Injectors from wire.go:

func InitializeResolver() *resolvers.Resolver {
	sampleUsecase := usecases.NewSampleUsecase()
	resolver := resolvers.NewResolver(sampleUsecase)
	return resolver
}
