package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/NishimuraTakuya-nt/go-graphql/internal/adapters/primary/graphql/dto"
)

// CreateSampleX is the resolver for the createSampleX field.
func (r *mutationResolver) CreateSampleX(ctx context.Context, input dto.CreateSampleXInput) (*dto.CreateSampleXPayload, error) {
	panic(fmt.Errorf("not implemented: CreateSampleX - createSampleX"))
}

// SampleX is the resolver for the sampleX field.
func (r *queryResolver) SampleX(ctx context.Context, id string) (*dto.SampleX, error) {
	panic(fmt.Errorf("not implemented: SampleX - sampleX"))
}
