package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/NishimuraTakuya-nt/go-graphql/internal/adapters/primary/graphql/dto"
	"github.com/NishimuraTakuya-nt/go-graphql/internal/adapters/primary/graphql/mapper"
)

// CreateSample is the resolver for the createSample field.
func (r *mutationResolver) CreateSample(ctx context.Context, input dto.CreateSampleInput) (*dto.CreateSamplePayload, error) {
	panic(fmt.Errorf("not implemented: CreateSample - createSample"))
}

// Sample is the resolver for the sample field.
func (r *queryResolver) Sample(ctx context.Context, id string) (*dto.Sample, error) {
	domainSample, err := r.sampleUsecase.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	d := mapper.ToDTO(domainSample)
	return d, nil
}
